functionsDirectory = "C:\\Users\\Clint\\Documents\\MakingWithKiro-ChoreChamp\\netlify\\functions"
functionsDirectoryOrigin = "ui"
headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\Clint\\Documents\\MakingWithKiro-ChoreChamp\\out"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\Clint\\Documents\\MakingWithKiro-ChoreChamp\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]